# Generated by Django 3.0.7 on 2020-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proverbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welsh', models.CharField(max_length=500)),
                ('english', models.CharField(max_length=500)),
            ],
        ),
    ]
