# Generated by Django 3.0.7 on 2020-06-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proverbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proverbs',
            new_name='Proverb',
        ),
    ]
